"""Reviewer Agent: independent code review for Programmer output."""

from __future__ import annotations

import json
from typing import Any

from mesh_agent.agents.base import StrongAgent

REVIEWER_PROMPT = """You are a **Scientific Code Reviewer** specialized in computational physics and numerical methods.

Your job: independently review code generated by the Programmer for correctness, numerical stability, and strategy fidelity.

**CRITICAL RULE**: You are an INDEPENDENT reviewer. Be skeptical. Do not assume the code is correct just because it was generated. Find every possible issue.

## Review Dimensions

### 1. Code Correctness
- Is the mesh generation logic correct? Will it produce valid cells?
- Are boundary conditions properly handled?
- Is the discretization appropriate for the physics?
- Are there off-by-one errors, wrong indices, or sign errors?

### 2. Strategy Fidelity
- Does the code faithfully implement the selected strategy?
- Are the target regions correctly identified?
- Are the target cell sizes and growth rates used as specified?

### 3. Numerical Stability
- Could the mesh changes cause CFL violations?
- Are aspect ratios controlled?
- Is the time step adjusted for the new mesh if needed?
- Could the refinement create near-degenerate cells?

### 4. Execution Safety
- Will the script run within reasonable time/memory?
- Are there infinite loops or unbounded operations?
- Are file paths correct?

## Output Format

```json
{
  "verdict": "pass|fail",
  "issues": [
    {
      "severity": "critical|major|minor",
      "dimension": "correctness|fidelity|stability|safety",
      "description": "Specific issue found",
      "suggestion": "How to fix it"
    }
  ],
  "summary": "Overall assessment"
}
```

If there are critical issues, the verdict MUST be "fail".
"""


class Reviewer(StrongAgent):
    """Independent code reviewer — MUST be a different LLM instance from Programmer."""

    def __init__(self, client=None):
        super().__init__("Reviewer", REVIEWER_PROMPT, client=client)

    async def review(
        self,
        strategy: dict[str, Any],
        mesh_script: str,
        post_script: str,
        solver_params: dict[str, Any],
        changes_summary: str,
    ) -> dict[str, Any]:
        user_message = f"""## Target Strategy
{json.dumps(strategy, indent=2)}

## Mesh Script
```python
{mesh_script}
```

## Solver Parameters
```json
{json.dumps(solver_params, indent=2)}
```

## Post-processing Script
```python
{post_script}
```

## Programmer's Change Summary
{changes_summary}

Review all code and parameters. Check correctness, strategy fidelity, numerical stability, and execution safety."""

        schema = {
            "type": "object",
            "properties": {
                "verdict": {"type": "string", "enum": ["pass", "fail"]},
                "issues": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "severity": {"type": "string", "enum": ["critical", "major", "minor"]},
                            "dimension": {"type": "string", "enum": ["correctness", "fidelity", "stability", "safety"]},
                            "description": {"type": "string"},
                            "suggestion": {"type": "string"},
                        },
                        "required": ["severity", "dimension", "description", "suggestion"],
                    },
                },
                "summary": {"type": "string"},
            },
            "required": ["verdict", "issues", "summary"],
        }

        return await self.run_structured(user_message, schema)

    async def review_solver(
        self,
        problem_spec: dict[str, Any],
        solver_code: str,
    ) -> dict[str, Any]:
        """Review a generated solver script for correctness and completeness."""
        user_message = f"""## Problem Specification
{json.dumps(problem_spec, indent=2)}

## Generated Solver
```python
{solver_code}
```

Review this solver script. Check:
1. Correctness: Does the numerical method match the PDE type? Are BCs handled correctly?
2. Completeness: Does it accept --mesh/--output-dir/--params? Does it write metrics.json?
3. Stability: Will it converge for reasonable inputs? Any CFL/timestep issues?
4. Executability: Can it run as `python solver.py --mesh <dir> --output-dir <dir> --params '{{}}'`?"""

        schema = {
            "type": "object",
            "properties": {
                "verdict": {"type": "string", "enum": ["pass", "fail"]},
                "issues": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "severity": {"type": "string", "enum": ["critical", "major", "minor"]},
                            "dimension": {"type": "string", "enum": ["correctness", "completeness", "stability", "executability"]},
                            "description": {"type": "string"},
                            "suggestion": {"type": "string"},
                        },
                        "required": ["severity", "dimension", "description", "suggestion"],
                    },
                },
                "summary": {"type": "string"},
            },
            "required": ["verdict", "issues", "summary"],
        }

        return await self.run_structured(user_message, schema)
