"""Reviewer Agent: independent code review for Programmer output."""

from __future__ import annotations

import json
from typing import Any

from mesh_agent.agents.base import StrongAgent

REVIEWER_PROMPT = """You are a **Scientific Code Reviewer** specialized in computational physics and numerical methods.

Your job: independently review code generated by the Programmer for correctness, numerical stability, and strategy fidelity.

## Severity Guidelines

- **critical**: ONLY for issues that make the code DEFINITELY non-executable — syntax errors, missing required arguments, `import` of non-existent modules, unbounded while(True). If the code will run but might have algorithmic issues, use "major".
- **major**: Algorithmic/logic errors that would produce wrong results — incorrect formula, wrong index, missing boundary condition handling.
- **minor**: Style issues, missing comments, variable naming, non-optimal but working approach.

## Review Dimensions

### 1. Code Correctness
- Will the script execute without Python errors?
- Are the required CLI arguments (--input-mesh, --output-dir) present?
- Are file I/O operations correct (read existing mesh, write new mesh)?

### 2. Strategy Fidelity
- Does the code implement the strategy's refinement/coarsening operations?
- Are the target regions approximately correct?

### 3. Numerical Stability
- Is the approach numerically reasonable?

### 4. Execution Safety
- Will the script run within reasonable time?
- Are file paths handled correctly?

## Output Format

```json
{
  "verdict": "pass|fail",
  "issues": [
    {
      "severity": "critical|major|minor",
      "dimension": "correctness|fidelity|stability|safety",
      "description": "Specific issue found",
      "suggestion": "How to fix it"
    }
  ],
  "summary": "Overall assessment"
}
```

Only set verdict to "fail" if there are critical issues (definitely non-executable code).
"""


class Reviewer(StrongAgent):
    """Independent code reviewer — MUST be a different LLM instance from Programmer."""

    def __init__(self, client=None):
        super().__init__("Reviewer", REVIEWER_PROMPT, client=client)

    async def review(
        self,
        strategy: dict[str, Any],
        mesh_script: str,
        post_script: str,
        solver_params: dict[str, Any],
        changes_summary: str,
    ) -> dict[str, Any]:
        user_message = f"""## Target Strategy
{json.dumps(strategy, indent=2)}

## Mesh Script
```python
{mesh_script}
```

## Solver Parameters
```json
{json.dumps(solver_params, indent=2)}
```

## Post-processing Script
```python
{post_script}
```

## Programmer's Change Summary
{changes_summary}

Review all code and parameters. Check correctness, strategy fidelity, numerical stability, and execution safety."""

        schema = {
            "type": "object",
            "properties": {
                "verdict": {"type": "string", "enum": ["pass", "fail"]},
                "issues": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "severity": {"type": "string", "enum": ["critical", "major", "minor"]},
                            "dimension": {"type": "string", "enum": ["correctness", "fidelity", "stability", "safety"]},
                            "description": {"type": "string"},
                            "suggestion": {"type": "string"},
                        },
                        "required": ["severity", "dimension", "description", "suggestion"],
                    },
                },
                "summary": {"type": "string"},
            },
            "required": ["verdict", "issues", "summary"],
        }

        return await self.run_structured(user_message, schema)

    async def review_solver(
        self,
        problem_spec: dict[str, Any],
        solver_code: str,
    ) -> dict[str, Any]:
        """Review a generated solver script for correctness and completeness."""
        user_message = (
            "## Problem Specification\n"
            + json.dumps(problem_spec, indent=2)
            + "\n\n## Generated Solver\n```python\n"
            + solver_code
            + "\n```\n\n"
            + "Review this solver script. Check:\n"
            + "1. Does it accept --mesh/--output-dir/--params? Write metrics.json?\n"
            + "2. Will it execute without Python errors?\n"
            + "Only mark issues as critical if the code definitely will not run."
        )

        schema = {
            "type": "object",
            "properties": {
                "verdict": {"type": "string", "enum": ["pass", "fail"]},
                "issues": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "severity": {"type": "string", "enum": ["critical", "major", "minor"]},
                            "dimension": {"type": "string", "enum": ["correctness", "completeness", "stability", "executability"]},
                            "description": {"type": "string"},
                            "suggestion": {"type": "string"},
                        },
                        "required": ["severity", "dimension", "description", "suggestion"],
                    },
                },
                "summary": {"type": "string"},
            },
            "required": ["verdict", "issues", "summary"],
        }

        return await self.run_structured(user_message, schema)
